using System;
using System.Collections.Generic;
using System.Text;

namespace Arch.Reports.Financials
{
    public class CompanieDTO
    {
        public string Id { get; set; }
        public string OrganizationalUnitId { get; set; }
        public string TenantId { get; set; }
        public string CompanyName { get; set; }
        public string CompanyAddress1 { get; set; }
        public string CompanyAddress2 { get; set; }
        public string CompanyAddress3 { get; set; }
        public string CompanyCity { get; set; }
        public string CompanyState { get; set; }
        public string CompanyZip { get; set; }
        public string CompanyCountry { get; set; }
        public string CompanyPhone { get; set; }
        public string CompanyFax { get; set; }
        public string CompanyEmail { get; set; }
        public string CompanyWebAddress { get; set; }
        public string CompanyLogoUrl { get; set; }
        public string CompanyLogoFilename { get; set; }
        public string CompanyShoppingCartURL { get; set; }
        public string CompanyReportsDirectoryURL { get; set; }
        public string CompanySupportDirectoryURL { get; set; }
        public string CompanyWebCRMDirectoryURL { get; set; }
        public string CompanyNotes { get; set; }
        public string CurrencyID { get; set; }
        public string BankAccount { get; set; }
        public string Terms { get; set; }
        public string FedTaxID { get; set; }
        public string StateTaxID { get; set; }
        public string VATRegistrationNumber { get; set; }
        public string VATSalesTaxID { get; set; }
        public string VATPurchaseTaxID { get; set; }
        public string VATOtherRegistrationNumber { get; set; }
        public string DefaultGLPostingDate { get; set; }
        public string DefaultSalesGLTracking { get; set; }
        public string DefaultGLPurchaseGLTracking { get; set; }
        public string DefaultSalesTaxGroup { get; set; }
        public string DefaultPurchaseTaxGroup { get; set; }
        public string DefaultInventoryCostingMethod { get; set; }
        public string AgeInvoicesBy { get; set; }
        public string AgePurchaseOrdersBy { get; set; }
        public string FinanceCharge { get; set; }
        public string FinanceChargePercent { get; set; }
        public string WarehouseID { get; set; }
        public string WarehouseBinID { get; set; }
        public string ShippingMethod { get; set; }
        public string ChargeHandling { get; set; }
        public string HandlingAsPercent { get; set; }
        public string HandlingRate { get; set; }
        public string ChargeMinimumSurcharge { get; set; }
        public string MinimumSurchargeThreshold { get; set; }
        public string GLAPAccount { get; set; }
        public string GLAPCashAccount { get; set; }
        public string GLAPInventoryAccount { get; set; }
        public string GLAPFreightAccount { get; set; }
        public string GLAPHandlingAccount { get; set; }
        public string GLAPMiscAccount { get; set; }
        public string GLAPDiscountAccount { get; set; }
        public string GLAPPrePaidAccount { get; set; }
        public string GLAPWriteOffAccount { get; set; }
        public string GLARAccount { get; set; }
        public string GLARCashAccount { get; set; }
        public string GLARSalesAccount { get; set; }
        public string GLARCOGSAccount { get; set; }
        public string GLARInventoryAccount { get; set; }
        public string GLARFreightAccount { get; set; }
        public string GLARHandlingAccount { get; set; }
        public string GLARDiscountAccount { get; set; }
        public string GLARMiscAccount { get; set; }
        public string GLARReturnAccount { get; set; }
        public string GLARWriteOffAccount { get; set; }
        public string GLFixedAccumDepreciationAccount { get; set; }
        public string GLFixedDepreciationAccount { get; set; }
        public string GLFixedAssetAccount { get; set; }
        public string GLFixedDisposalAccount { get; set; }
        public string GLBankInterestEarnedAccount { get; set; }
        public string GLBankServiceChargesAccount { get; set; }
        public string GLBankMiscWithdrawlAccount { get; set; }
        public string GLBankBankMisDepositAccount { get; set; }
        public string GLBankOtherChargesAccount { get; set; }
        public string GLRetainedEarningsAccount { get; set; }
        public string GLProfitLossAccount { get; set; }
        public string GLUnrealizedCurrencyProfitLossAccount { get; set; }
        public string GLRealizedCurrencyProfitLossAccount { get; set; }
        public string GLARFreightProfitLossAccount { get; set; }
        public string GLCurrencyGainLossAccount { get; set; }
        public string GLUnrealizedCurrencyGainLossAccount { get; set; }
        public string FiscalStartDate { get; set; }
        public string FiscalEndDate { get; set; }
        public string CurrentFiscalYear { get; set; }
        public string CurrentPeriod { get; set; }
        public string Period1Date { get; set; }
        public string Period2Date { get; set; }
        public string Period3Date { get; set; }
        public string Period4Date { get; set; }
        public string Period5Date { get; set; }
        public string Period6Date { get; set; }
        public string Period7Date { get; set; }
        public string Period8Date { get; set; }
        public string Period9Date { get; set; }
        public string Period10Date { get; set; }
        public string Period11Date { get; set; }
        public string Period12Date { get; set; }
        public string Period13Date { get; set; }
        public string Period14Date { get; set; }
        public string Period1Closed { get; set; }
        public string Period2Closed { get; set; }
        public string Period3Closed { get; set; }
        public string Period4Closed { get; set; }
        public string Period5Closed { get; set; }
        public string Period6Closed { get; set; }
        public string Period7Closed { get; set; }
        public string Period8Closed { get; set; }
        public string Period9Closed { get; set; }
        public string Period10Closed { get; set; }
        public string Period11Closed { get; set; }
        public string Period12Closed { get; set; }
        public string Period13Closed { get; set; }
        public string Period14Closed { get; set; }
        public string GAAPCompliant { get; set; }
        public string EditGLTranssactions { get; set; }
        public string EditBankTransactions { get; set; }
        public string EditAPTransactions { get; set; }
        public string EditARTransactions { get; set; }
        public string HardClose { get; set; }
        public string AuditTrail { get; set; }
        public string PeriodPosting { get; set; }
        public string SystemDates { get; set; }
        public string LockedBy { get; set; }
        public string LockTS { get; set; }
        public string AlternateCurrencyID { get; set; }
        public string LastEditDate { get; set; }
        public string CreationDate { get; set; }
        public string AllowTransactionDate { get; set; }
        public string PasswordAttempt { get; set; }
        public string PasswordDuration { get; set; }
        public string DisbursedToIssue { get; set; }
        public string Erp_DefaultCashAccount { get; set; }
        public string Erp_DefaultPriceMatrix { get; set; }
        public string Erp_TrackLot { get; set; }
        public string Erp_GLAcctMaxXter { get; set; }
        public string Erp_GLAccountMasking { get; set; }
        public string Erp_UseAccountSegmentation { get; set; }
        public string Erp_NoOfSegmentation { get; set; }
        public string Erp_ToOrganizationalUnitId { get; set; }
        public string Erp_ToDivisionID { get; set; }
        public string Erp_ToTenantId { get; set; }
        public string IsDeleted { get; set; }
        public string LastModificationTime { get; set; }
        public string LastModifierUserId { get; set; }
        public string CreationTime { get; set; }
        public string CreatorUserId { get; set; }
        public string PrinterCheck { get; set; }
        public string Erp_ToCompanyID { get; set; }
        public string Erp_ToDepartmentID { get; set; }
        public string PeriodDate { get; set; }
        public string ConversionRate { get; set; }
        public string ConversionCurrencyID { get; set; }
    }
}
